# BACKGROUND
background {
    monitor =
    path = /home/gio/Downloads/fireplace_static.jpg
    blur_passes = 2
    blur_size = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Time-Hour
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H")</span>"
    color = rgba(57, 74, 82, 1.0)
    font_size = 125
    font_family = Inter Bold
    position = -80, 190
    halign = center
    valign = center
}

# Time-Minute
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%M")</span>"
    color = rgba(255, 255, 255, 1.0)
    font_size = 125
    font_family = Inter Bold
    position = 0, 70
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d %B, %a.")"
    color = rgba(70, 82, 103, 1.0)
    font_size = 22
    font_family = Inter Bold
    position = 20, -8
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = rgba(255, 255, 255, 1.0)
    font_size = 22
    font_family = Inter Bold
    position = 0, -220
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.18
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(70, 82, 103, 1.0)
    inner_color = rgba(134, 190, 206, 0.1)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    font_family = Inter Bold
    placeholder_text = <i><span foreground="##ffffff99">wgmi</span></i>
    hide_input = false
    position = 0, -290
    halign = center
    valign = center
}
